export const sagaActions = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	SINGIN: "SIGNIN",
	SINGUP: "SINGUP",
	ISSIGNUP: "ISSIGNUP",
	ISSIGNUP: "ISSIGNUP",
	ISLOGGEDIN: "ISLOGGEDIN",
	ISMODALOPEN: "ISMODALOPEN",
};
